// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as UseLocalStorageJs from "./useLocalStorage.js";
import UseLocalStorageJs$1 from "./useLocalStorage.js";

function concatArray(x) {
  return Core__Array.reduce(x, [], (function (a, c) {
                return a.concat(c);
              }));
}

function useLocalStorage(prim0, prim1) {
  return UseLocalStorageJs$1(prim0, prim1);
}

function useLocalStorageListener(prim0, prim1) {
  return UseLocalStorageJs.useLocalStorageListener(prim0, prim1);
}

function useStateWithGetter(initial) {
  var match = React.useState(initial);
  var state = match[0];
  var stateRef = React.useRef(state);
  React.useEffect((function () {
          stateRef.current = state;
        }), [state]);
  var getState = function () {
    return stateRef.current;
  };
  return [
          state,
          match[1],
          getState
        ];
}

function monthToEmoji(m) {
  switch (m) {
    case 0 :
        return "❄️";
    case 1 :
        return "❤️";
    case 2 :
        return "🍀";
    case 3 :
        return "🌧️";
    case 4 :
        return "🌷";
    case 5 :
        return "☀️";
    case 6 :
        return "🍉";
    case 7 :
        return "🏖️";
    case 8 :
        return "📚";
    case 9 :
        return "🎃";
    case 10 :
        return "🍁";
    case 11 :
        return "🎄";
    default:
      return "";
  }
}

var standardDateFormat = "y-MM-dd";

export {
  concatArray ,
  useLocalStorage ,
  useLocalStorageListener ,
  standardDateFormat ,
  useStateWithGetter ,
  monthToEmoji ,
}
/* react Not a pure module */
