// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as UseLocalStorageJs from "./useLocalStorage.js";
import UseLocalStorageJs$1 from "./useLocalStorage.js";

function useLocalStorage(prim0, prim1) {
  return UseLocalStorageJs$1(prim0, prim1);
}

function useLocalStorageListener(prim0, prim1) {
  return UseLocalStorageJs.useLocalStorageListener(prim0, prim1);
}

function useStateWithGetter(initial) {
  var match = React.useState(initial);
  var state = match[0];
  var stateRef = React.useRef(state);
  React.useEffect((function () {
          stateRef.current = state;
        }), [state]);
  var getState = function () {
    return stateRef.current;
  };
  return [
          state,
          match[1],
          getState
        ];
}

var standardDateFormat = "y-MM-dd";

export {
  useLocalStorage ,
  useLocalStorageListener ,
  standardDateFormat ,
  useStateWithGetter ,
}
/* react Not a pure module */
