// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

function getElementByClassOp(s) {
  return Core__Option.flatMap(Caml_option.nullable_to_opt(document.getElementsByClassName(s)), (function (x) {
                return x[0];
              }));
}

function getElementByIdOp(s) {
  return Caml_option.nullable_to_opt(document.getElementById(s));
}

var Derived = {
  getElementByClassOp: getElementByClassOp,
  getElementByIdOp: getElementByIdOp
};

export {
  Derived ,
}
/* No side effect */
