// Generated by ReScript, PLEASE EDIT WITH CARE


var Flower = {};

var Snowflake = {};

var Leaf = {};

var Umbrella = {};

var Lock = {};

var LockOpen = {};

var EyeClosed = {};

var Eye = {};

var Sun = {};

var Moon = {};

var Trash = {};

var Calendar = {};

var CalendarX = {};

var ChevronRightCompact = {};

export {
  Flower ,
  Snowflake ,
  Leaf ,
  Umbrella ,
  Lock ,
  LockOpen ,
  EyeClosed ,
  Eye ,
  Sun ,
  Moon ,
  Trash ,
  Calendar ,
  CalendarX ,
  ChevronRightCompact ,
}
/* No side effect */
