// Generated by ReScript, PLEASE EDIT WITH CARE


var Flower = {};

var Snowflake = {};

var Leaf = {};

var Umbrella = {};

var Lock = {};

var LockOpen = {};

var EyeClosed = {};

var Eye = {};

export {
  Flower ,
  Snowflake ,
  Leaf ,
  Umbrella ,
  Lock ,
  LockOpen ,
  EyeClosed ,
  Eye ,
}
/* No side effect */
