// Generated by ReScript, PLEASE EDIT WITH CARE

import DropdownJsx from "./Dropdown.jsx";
import * as JsxRuntime from "react/jsx-runtime";

var make = DropdownJsx;

var Dropdown = {
  make: make
};

function MenuBar$SmallBar(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(make, {
                    onSort: props.onSort,
                    onExportFile: props.onExportFile,
                    onExportFolder: props.onExportFolder,
                    onShow: props.onShow,
                    onHide: props.onHide,
                    onLock: props.onLock,
                    onUnlock: props.onUnlock,
                    theme: props.theme,
                    setTheme: props.setTheme
                  }),
              className: "text-xs flex-none border-b border-[--foreground-300] flex flex-row items-center"
            });
}

var SmallBar = {
  make: MenuBar$SmallBar
};

export {
  Dropdown ,
  SmallBar ,
}
/* make Not a pure module */
