// Generated by ReScript, PLEASE EDIT WITH CARE


var data = "megalog-data";

var startYear = "megalog-start-year";

var endYear = "megalog-end-year";

var theme = "megalog-theme";

export {
  data ,
  startYear ,
  endYear ,
  theme ,
}
/* No side effect */
