// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Common from "./Common.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Color from "@texel/color";
import * as JsxRuntime from "react/jsx-runtime";

function hsv(h, s, v) {
  return Color.RGBToHex(Color.convert([
                  h,
                  s,
                  v
                ], Color.OKHSV, Color.sRGB));
}

function hsl(h, s, l) {
  return Color.RGBToHex(Color.convert([
                  h,
                  s,
                  l
                ], Color.OKHSL, Color.sRGB));
}

function customMonthHue(monthInt, param) {
  switch (monthInt) {
    case 1 :
        return 210;
    case 3 :
        return 270;
    case 4 :
        return 120;
    case 6 :
        return 80;
    case 7 :
        return 40;
    case 5 :
    case 8 :
        return 240;
    case 9 :
        return 180;
    case 10 :
        return 60;
    case 11 :
        return 340;
    case 12 :
        return 150;
    default:
      return 0;
  }
}

function weekColor(weekInt) {
  var weekPercent = weekInt / 53;
  return hsv(weekPercent * 360, 1.0, 1.0);
}

function monthHue(monthInt) {
  return 360 / 12 * Math.imul(monthInt - 3 | 0, 5) % 360.0;
}

var monthColors = Core__Array.make(12, false).map(function (param, i) {
      return hsl(monthHue(i), 1.0, 0.55);
    });

var monthColorsDim = Core__Array.make(12, false).map(function (param, i) {
      return hsl(monthHue(i), 1.0, 0.8);
    });

function monthColor(monthInt) {
  return monthColors[monthInt - 1 | 0];
}

function monthDimColor(monthInt) {
  return monthColorsDim[monthInt - 1 | 0];
}

var Light = {
  monthColors: monthColors,
  monthColorsDim: monthColorsDim,
  monthColor: monthColor,
  monthDimColor: monthDimColor
};

var monthColors$1 = Core__Array.make(12, false).map(function (param, i) {
      return hsl(monthHue(i), 1.0, 0.7);
    });

var monthColorsDim$1 = Core__Array.make(12, false).map(function (param, i) {
      return hsl(monthHue(i), 1.0, 0.4);
    });

function monthColor$1(monthInt) {
  return monthColors$1[monthInt - 1 | 0];
}

function monthDimColor$1(monthInt) {
  return monthColorsDim$1[monthInt - 1 | 0];
}

var Dark = {
  monthColors: monthColors$1,
  monthColorsDim: monthColorsDim$1,
  monthColor: monthColor$1,
  monthDimColor: monthDimColor$1
};

function monthVar(month) {
  return "var(--m" + month.toString() + ")";
}

function monthDimVar(month) {
  return "var(--m" + month.toString() + "dim)";
}

function getTheme() {
  return Common.useLocalStorageListener("theme", "light");
}

function colorsByTheme(theme) {
  if (theme === "dark") {
    return [
            monthColor$1,
            monthDimColor$1
          ];
  } else {
    return [
            monthColor,
            monthDimColor
          ];
  }
}

function Theme$Styling(props) {
  var theme = Common.useLocalStorageListener("theme", "dark");
  var match = colorsByTheme(theme);
  var monthDimColor = match[1];
  var monthColor = match[0];
  var colors = Core__Array.make(12, false).map(function (param, i) {
          return "--m" + (i + 1 | 0).toString() + ": " + monthColor(i + 1 | 0) + ";";
        }).join(" ");
  var colorsDim = Core__Array.make(12, false).map(function (param, i) {
          return "--m" + (i + 1 | 0).toString() + "dim: " + monthDimColor(i + 1 | 0) + ";";
        }).join(" ");
  return JsxRuntime.jsx("style", {
              children: ":root {" + colors + " " + colorsDim + "}"
            });
}

var Styling = {
  make: Theme$Styling
};

function useTheme() {
  var match = Common.useLocalStorage("theme", "dark");
  var theme = match[0];
  React.useEffect((function () {
          if (theme === "dark") {
            document.documentElement.classList.remove("light");
            document.documentElement.classList.add("dark");
          } else {
            document.documentElement.classList.remove("dark");
            document.documentElement.classList.add("light");
          }
        }), [theme]);
  return [
          theme,
          match[1]
        ];
}

export {
  hsv ,
  hsl ,
  customMonthHue ,
  weekColor ,
  monthHue ,
  Light ,
  Dark ,
  monthVar ,
  monthDimVar ,
  getTheme ,
  colorsByTheme ,
  Styling ,
  useTheme ,
}
/* monthColors Not a pure module */
